### ISSUE TITLE
pyros_interfaces_ros fails to build

### ISSUE THREAD

**Issue by tfoote** [asmodehn/pyros-rosinterface#17]
The pyros_interfaces_ros package is failing to build. I believe that there's a python dependency that has changed to default to python3 and will need to be pinned to an older version that supports python2 to keep working. 

For example: http://build.ros.org/job/Kbin_uX32__pyros_interfaces_ros__ubuntu_xenial_i386__binary/13/

```
16:07:43 Collecting more-itertools>=4.0.0 (from pytest>=2.9.1->pyzmp>=0.0.17->pyros-interfaces-ros==0.4.2)
16:07:43   Downloading https://files.pythonhosted.org/packages/67/4a/16cb3acf64709eb0164e49ba463a42dc45366995848c4f0cf770f57b8120/more-itertools-8.4.0.tar.gz (83kB)
16:07:43     Complete output from command python setup.py egg_info:
16:07:43     Traceback (most recent call last):
16:07:43       File "<string>", line 1, in <module>
16:07:43       File "/tmp/pip-build-YojELt/more-itertools/setup.py", line 5, in <module>
16:07:43         from more_itertools import __version__
16:07:43       File "more_itertools/__init__.py", line 1, in <module>
16:07:43         from .more import *  # noqa
16:07:43       File "more_itertools/more.py", line 161
16:07:43         ) from e
16:07:43              ^
16:07:43     SyntaxError: invalid syntax
```

This is the only known regression in Kinetic for the pending sync. https://discourse.ros.org/t/preparing-for-kinetic-sync-2020-08-20/16002

If it's not resolved we will remove it before the sync next week.

**Comment by asmodehn** [comment]
Hi Tully,

Thanks for letting me know.
It seems more-itertools does not support python2 since version 6.0.0.
However I have yet to find which package in the chain includes it as its
dependency and where (maybe latest pytest being too new for EOL'd python2 ?)

Anyway I currently don't have any spare time to fix Python2 issues as this
version has been EOL for a while already.
So feel free to remove it from the kinetic packages. (There might be others
packages depending on it - especially among
http://repositories.ros.org/status_page/ros_kinetic_default.html?q=AlexV).

I do not know of any other package depending on pyros, at least on kinetic.
If any interest arise I can provide some guidance... otherwise I won't look
into it in the foreseeable future.

Cheers,
--
AlexV

**Comment by tfoote** [comment]
Thanks for letting me know you won't have time. I'll pull it from the distro then. https://github.com/ros/rosdistro/pull/26257
